apiVersion: v1
kind: Pod
metadata:
  name: amazonlinux-2022
spec:
  containers:
  - name: amazonlinux-2022
    image: public.ecr.aws/amazonlinux/amazonlinux:2022
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
