apiVersion: v1
kind: Pod
metadata:
  name: amazonlinux
spec:
  containers:
  - name: amazonlinux
    image: public.ecr.aws/amazonlinux/amazonlinux:latest
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
