apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: app
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1b: { id: subnet-0cf9b89829411f5ab }
      us-east-1a: { id: subnet-036de13322627718d }

iam:
  withOIDC: true

managedNodeGroups:
  - name: ng-spot-workers
    spot: true
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    privateNetworking: true
    ssh:
      publicKeyName: scottliao

nodeGroups:
  - name: ng-1-workers
    instanceType: m5.large
    desiredCapacity: 1
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
    ssh:
      publicKeyName: scottliao
