apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: app-demo
  region: us-east-1
  version: "1.19"

vpc:
  subnets:
    private:
      us-east-1b: { id: subnet-0cf9b89829411f5ab }
      us-east-1a: { id: subnet-036de13322627718d }

iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    desiredCapacity: 2
    instanceType: m5.large
    privateNetworking: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
    ssh:
      allow: true
      publicKeyName: scottliao

# managedNodeGroups:
#   - name: ng-1-workers
#     spot: true
#     minSize: 1
#     maxSize: 3
#     instanceType: m5.large
#     desiredCapacity: 1
#     privateNetworking: true
#     iam:
#       withAddonPolicies:
#         autoScaler: true
#     ssh:
#       publicKeyName: scottliao

# To enable all of the control plane logs, uncomment below:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]