apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::694944685669:role/eksctl-eksworkshop-eksctl-nodegro-NodeInstanceRole-1C8K8KHM7ZN8G
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
