apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    50:
      - EksNodeGroup-x86_64
    10:
      - EksNodeGroup-arm64
