apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    10:
      - .*EksNodeGroup-x86_64.*
    50:
      - .*EksNodeGroup-arm64.*
