apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-arm64
  namespace: graviton2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-arm64
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

