---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-apache2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-apache2
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-apache2
    spec:
      containers:
      - image: public.ecr.aws/ubuntu/apache2:latest
        imagePullPolicy: Always
        name: app-apache2
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/arch: arm64
---
apiVersion: v1
kind: Service
metadata:
  name: app-apache2
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-apache2
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-apache2
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: app-apache2
              servicePort: 80
